EvilProject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EvilProject.Models;


namespace EvilProject.Controllers
{
    public class HomeController : BaseContro
    {
        private EP_DB db = new EP_DB();
        string wyj = "";
        [AllowAnonymous]
        public ActionResult Index()
        {
            try
            {
                ViewData.Add("EX", "przed");


                var lista =  db.PageNewses.ToList().OrderBy(m => m.publish_date);
                if (lista != null)
                {
                    foreach (PageNews news in lista)
                    {
                        if (news.body.Length > 700)
                            news.body = news.body.Substring(0, 700) + "...";
                    }

                    ViewData.Add("News", lista);
                }
               
                ViewData["EX"] = "po";
            }
            catch (Exception ex)
            {
                wyj = ex.Message;
            }
            finally
            {
                ViewData["EX"] = wyj;
            }
            return View();
        }

        [AllowAnonymous]
        public ActionResult About()
        {
           // ViewBag.Message = "Your app description page.";
            
            return View();
        }

        [AllowAnonymous]
        public ActionResult Contact()
        {
           // ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

EvilProject/Controllers/PageNewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EvilProject.Models;

namespace EvilProject.Controllers
{
    
    public class PageNewsController : BaseContro
    {
        private EP_DB db = new EP_DB();

        //
        // GET: /PageNews/
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Upload(HttpPostedFileBase uploadFile, string CKEditorFuncNum, string CKEditor, string langCode)
        {
            string url; // url to return
            string message =""; // message to display (optional)
            string filePath = "";

            try
            {
                if (((System.Web.HttpRequestWrapper)(Request)).Files[0] != null)
                {

                    filePath = Path.Combine(HttpContext.Server.MapPath("~/Content/images/upload"), Path.GetFileName(((System.Web.HttpRequestWrapper)(Request)).Files[0].FileName));
                    ((System.Web.HttpRequestWrapper)(Request)).Files[0].SaveAs(filePath);
                    filePath = "/Content/images/upload/" + ((System.Web.HttpRequestWrapper)(Request)).Files[0].FileName;
                    message = "Image was saved correctly";
                }
            }
            catch (Exception ex)
            {
                message = ex.Message;
            }

            url = Request.Url.GetLeftPart(UriPartial.Authority) + "/" + filePath;
            // passing message success/failure
            
            
            string output = @"<html><body><script>window.parent.CKEDITOR.tools.callFunction(" + CKEditorFuncNum + ", \"" + url + "\", \"" + message + "\");</script></body></html>";
            return Content(output);
            //return Redirect(Request.UrlReferrer.AbsoluteUri);
        }

        public ActionResult Index()
        {
            return View(db.PageNewses.ToList().OrderByDescending(m=>m.publish_date));
        }

        //
        // GET: /PageNews/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id = 0)
        {
            PageNews pagenews = db.PageNewses.Find(id);
            if (pagenews == null)
            {
                return HttpNotFound();
            }
            return View(pagenews);
        }

        //
        // GET: /PageNews/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /PageNews/Create

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(PageNews pagenews)
        {
            if (ModelState.IsValid)
            {
                db.PageNewses.Add(pagenews);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(pagenews);
        }

        //
        // GET: /PageNews/Edit/5

        public ActionResult Edit(int id = 0)
        {
            PageNews pagenews = db.PageNewses.Find(id);
            if (pagenews == null)
            {
                return HttpNotFound();
            }
            return View(pagenews);
        }

        //
        // POST: /PageNews/Edit/5

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(PageNews pagenews)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pagenews).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pagenews);
        }

        //
        // GET: /PageNews/Delete/5

        public ActionResult Delete(int id = 0)
        {
            PageNews pagenews = db.PageNewses.Find(id);
            if (pagenews == null)
            {
                return HttpNotFound();
            }
            return View(pagenews);
        }

        //
        // POST: /PageNews/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            PageNews pagenews = db.PageNewses.Find(id);
            db.PageNewses.Remove(pagenews);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

EvilProject/Views/Home/About.cshtml
@{
    ViewBag.Title = "O mnie";
}


<div class="post">
	<div class="entry">
		<p>
           TODO
		</p>
	</div>
</div>

EvilProject/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Kontakt";
}

<div class="post">
	<div class="entry">
		<p>
           TODO
		</p>
	</div>
</div>

EvilProject/Views/Home/Index.cshtml
    
@{
    ViewBag.Title = "Główna";
}



@{

    String.Format("{0}", ViewData["EX"]);
    var Model = ViewData["News"] as IEnumerable<EvilProject.Models.PageNews>;
    if (Model != null)
    {
        foreach (var item in Model) {
            <div class="post">
	        <h1 class="title"><a href="#"> @Html.DisplayTextFor(modelItem => item.title)</a></h1>
	        <p class="byline"><small>  @String.Format("{0}", item.publish_date.ToString("yyyy-MM-dd HH:mm")) <a href="#">Broda Samo Zło</a></small></p>
	        <div class="entry">
                    @if(Request.IsAuthenticated) 
                    {<p>   
                        @Html.ActionLink("Edit", "Edit", "PageNews", new { item.id }, new { @class = "editlinksmall" })
                        @Html.ActionLink("Delete", "Delete", "PageNews", new { item.id }, new { @class = "deletelinksmall" })
                     </p>
                    }
		            <p>
                        @if(item.body.Length >= 700)
                        {
                            @Html.DisplayTextFor(modelItem => item.body)
                            <p class="links">@Html.ActionLink("Czytaj dalej...", "Details", "PageNews", new { item.id }, new { @class = "more" })</p>
                        }
                        else
                        {
                            @Html.DisplayTextFor(modelItem => item.body)
                        }
		            </p>
	            </div>
            </div>
    
        }
    }
    else
    {
        String.Format("Model == null");
    }
    
      if(Request.IsAuthenticated) 
        {<p>   
            @Html.ActionLink("Dodaj", "Create", "PageNews",null,  new { @class = "addlinksmall" })
         </p>
        }
    
}

<!--
<div class="post">
	<h1 class="title"><a href="#">Witam na mojej stronie!</a></h1>
	<p class="byline"><small>2013-01-11 <a href="#">Broda Samo Zło</a></small></p>
	<div class="entry">
		<p>
            Ta strona, jak i strony zrobione w PHP (patrz z lewej) powstały jako projekty badawczo - rozwojowe. Główny cel dla mnie to nauczyć się, poprzez praktykę, wzorca projektowego MVC, zarówno w środowisku ASP jak i PHP.<br>
            Ta strona powstaje z wykorzystaniem tylko i wyłącznie technologii dostarczonych przez <strong>M</strong>icro<strong>S</strong>oft -  ASP.NET MVC4, kod pisany jest w C# w  środowisku MS Visual Studio 2012 Express, baza danych MS SQL Express.<br>
            Strony PHP-owe pisane są w PHP(taa wiem że to dziwne ;)), w środowisku Eclipse(Juno) i wykorzystaniem baz w MySQL. Upraszczając, na tej stronie 'ćwiczę' MS-a, na projektach z lewej PHP-a.
            <br >
            Świadomie całkowicie pomijam jako cel nauki (chociaż też pewnie przy okazji trochę się nauczę) HTML/CSS - jestem tzw. totalnym bezguściem artystycznym.. 
            tego nie zmienię, to jedna z rzeczy których człowiek nie jest w stanie się nauczyć... albo <strong>'TO'</strong> masz albo nie... chociaż od strony czysto 'technicznej' HTML i CSS są proste jak
            kontrtukcja gwoździa...<br>
            Czym będzie TA strona? Jeszcze nie wiem... może będę tu wpisywał swoje przejścia, czy generalnie problemy/trudności jakie miałem przy tworzeniu poszczególnych rozwiązań.. zobaczymy...<br >
            Postaram się każdą rzecz z TODO, po wykonaniu, krótko(albo i długo, jak będzie wena) opisać w poście. Jakie były trudności, strony na których szukałem pomocy itd, itp..<br>
            TODO będzie zwierało mój plan na najbliższe dni, będzie tu info nie tylko o rzeczach które chcę wykonać dla tej strony ale także dla info dla stron PHP-owych.
		</p>
	</div>
</div>


<div class="post">
	<h1 class="title"><a href="#">Hosting</a></h1>
	<p class="byline"><small>2013-01-11 <a href="#">Broda Samo Zło</a></small></p>
	<div class="entry">
		<p>
            Ta strona to moja pierwsza w życiu zarejestrowana domena :D. <br>
            Wszysto co widać jesto hostowane jest na serwerach <a href="http://www.webio.pl" target='blank'>Webio</a>, to mój pierwszy kontakt z jakim kolwiek dostwcą usług hostingowych, oferują hosting PHP i ASP za naprawdę rozsądną cenę (130zł/rok w momencie pisania tego posta). 
            Muszę przyznać, że jestem mile zaskoczony prostotą całego przedsięwzięcia. Zarejestruj konto -> Dodaj domenę (może być jako ich poddomena) -> Włącz zdalną publikację -> Opublikuj stronę. Szybko , łatwo i przyjemnie :D
		</p>
	</div>
</div>



<div class="post">
	<h1 class="title"><a href="#">....</a></h1>
	<p class="byline"><small>2013-01-14 <a href="#">Broda Samo Zło</a></small></p>
	<div class="entry">
		<p>
            Priorytet to zrobić na tej stronce logowanie i dodawanie treści.. zwłaszcza dla panelu z prawej strony...
		</p>
	</div>
</div>

-->